### ISSUE TITLE
Cannot mock concrete classes with Mockito

### ISSUE THREAD

**Issue by DariusL** [linkedin/dexmaker#20] opened 2015-07-28 15:32 UTC
I'm getting 

```
java.lang.NoClassDefFoundError: com/android/dx/stock/ProxyBuilder
```

or

```
java.lang.ExceptionInInitializerError
```

when I try to mock a concrete class on dexmaker 1.4 or 1.3. Reverting to 1.2 from google code works fine.

```
java.lang.NoClassDefFoundError: com/android/dx/stock/ProxyBuilder
at com.android.dx.mockito.DexmakerMockMaker.createMock(DexmakerMockMaker.java:56)
at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
at org.mockito.Mockito.mock(Mockito.java:1285)
at org.mockito.Mockito.mock(Mockito.java:1163)
at lt.segfoltas.asthmacontroltest.DbAsyncTests.setUp(DbAsyncTests.java:28)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)


java.lang.ExceptionInInitializerError
at com.android.dx.mockito.DexmakerMockMaker.createMock(DexmakerMockMaker.java:56)
at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
at org.mockito.Mockito.mock(Mockito.java:1285)
at org.mockito.Mockito.mock(Mockito.java:1163)
at lt.segfoltas.asthmacontroltest.DbAsyncTests.setUp(DbAsyncTests.java:28)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1584)
Caused by: java.lang.ExceptionInInitializerError
at com.android.dx.stock.ProxyBuilder.<clinit>(ProxyBuilder.java:758)
... 15 more
Caused by: java.lang.NoClassDefFoundError: com.android.dx.rop.type.Type
at com.android.dx.TypeId.<clinit>(TypeId.java:36)
... 16 more
```

Mocking interfaces works as before. I'd just use 1.2, but I hit #12 on lollipop.

**Comment by sek** [comment] 2015-08-20 11:33
FYI: This error is demonstrated by this sample project: https://github.com/sek/MockitoOnAndroidDemo

**Comment by vaughandroid** [comment] 2015-08-26 16:26
+1 I've seen similar issues. Ran into them when 1.3/1.4 came out but haven't found time to investigate fully.
If memory serves, I think it looked like there was some reflection going on to find classes which have since been repackaged.

**Comment by vaughandroid** [comment] 2015-09-10 08:14
It turns out that all I was missing is a dependency on the new(?) `dexmaker-dx` module. This is a new requirement in 1.3/1.4, but hasn't been mentioned anywhere that I've seen.

**Comment by DariusL** [comment] 2015-09-10 09:33
Can confirm, fixes the issue. All my tests pass on:
* Nexus 5 API 22
* Genymotion API 16
* Genymotion API 21

If the proposed solution would be to add another dependency, this should probably be mentioned in the readme.

**Comment by trebouillon** [comment] 2016-01-15 10:05
Adding dexmaker-dx dependency fixed my issue as well.

**Comment by drewhannay** [comment] 2016-12-01 15:51
Closing this one as a duplicate of #22

**Closed by drewhannay** 2016-12-01 15:51 UTC
